;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-newline
        autopair-skip-close-maybe
        end-of-visual-line
        kill-region
        magit-status
        org-end-of-line
        org-self-insert-command
        rectangle-next-line
        rectangle-right-char
        undo-tree-visualize
        ))

(setq mc/cmds-to-run-once
      '(
        save-buffers-kill-terminal
        ))
